### PR TITLE
Archives

### LINKED ISSUE #187: Get a document's children
Get up to a certain number of a documents direct children and return the result in the api response

Part of #166

### PR DESCRIPTION
**Pull request by Danwhy**
Displays direct children of documents in the browse this archive section at the bottom of the page.
Children of children are displayed when the + is clicked on. This makes a request to the server with an 'expanded' query and receives the page with the new children displayed.

No ajax functionality yet

ref #166, #191 
closes #187

### CODE REVIEW

**Comment by Danwhy** [comment]
Just going to rebase this PR, then it's ready

**Comment by nelsonic** [comment]
@Danwhy please resolve merge conflicts and assign when ready. :

**Comment by nelsonic** [comment]
@Danwhy #mindreader

**Comment by Danwhy** [comment]
@nelsonic If Travis passes, this is ready for review

**Comment by Danwhy** [comment]
Now included in #202

**Pull request closed without merging**
