### PR TITLE
Relevance improvements

### PR DESCRIPTION
**Pull request by Danwhy**
Explanation of the queries: https://github.com/TheScienceMuseum/collectionsonline/wiki/Search-Query

### CODE REVIEW

**Comment by alanshaw** [comment]
@Danwhy could you explain the changes you've made to the query and the effect it'll have?

**Comment by Danwhy** [comment]
:+1: Written them up here : https://github.com/TheScienceMuseum/collectionsonline/wiki/Search-Query

**Comment by alanshaw** [comment]
👓

**Comment by alanshaw** [comment]
LGTM

**Pull request merged**
