### PR TITLE
replace typeahead with awesomplete

### PR DESCRIPTION
**Pull request by SimonLab**
see #328
@tobystokes I've modified the css of awesomplete in [this file](https://github.com/TheScienceMuseum/collectionsonline/blob/typeahead-remove/client/styles/components/_awesomplete.scss) if you want to have a look.

@Danwhy @nelsonic ready for review

### CODE REVIEW

**Comment by tobystokes** [comment]
ok, i'll take a look.

**Comment by Danwhy** [comment]
nice, LGTM

**Comment by SimonLab** [comment]
@tobystokes Thanks for the review! LGTM!

**Comment by nelsonic** [comment]
Great work  (_again_!)

**Pull request merged**
