### PR TITLE
Missing galleries 

### PR DESCRIPTION
**Pull request by Danwhy**
ref #584

Adds the new galleries, and adds script to fetch new galleries, to be run whenever the index is updated

### CODE REVIEW

**Comment by iteles** [comment]
@danwhy Do we know why the coverage dropped here?

**Comment by jamieu** [comment]
Hi Dan, what script needs updating to get the new values?

**Comment by Danwhy** [comment]
@iteles @nelsonic The coverage hasn't dropped, has it?
screen shot 2016-11-16 at 15 50 51
The coverage has been at about 98% for a while because the tests for the code that gets the images are still commented out

**Comment by nelsonic** [comment]
@Danwhy yeah, on the last few PRs before our end-of-phase1 I noted that/_why_ coverage was `<100%` and we agreed that as soon as time/budget was allocated we should focus on getting those tests re-worked. 👍 
This fix looks good and it's _needed_ so I'm merging. 
(_hope that's OK @SimonLab ..._)

**Comment by SimonLab** [comment]
@Danwhy thanks for this PR, @nelsonic sorry I've been busy with other tasks I reviewed the PR but forget to approve it.

**Comment by nelsonic** [comment]
@SimonLab that's what I thought... 😉 
Don't worry, I _know_ you are busy. 👍 
Thanks all! 🎉

**Pull request merged**
