### PR TITLE
crop, don't stretch thumbnail images - fixes #727

### LINKED ISSUE #727: Crop carousel thumbnails (rather than squish)
http://collection.sciencemuseum.org.uk/objects/co498436/distended-human-skull-labelled-ln-fowler-for-phr-human-remains-skull

screen shot 2016-12-14 at 15 46 28

### PR DESCRIPTION
**Pull request by tobystokes**
heh, fixed without leaving github website :)

### CODE REVIEW

**Comment by nelsonic** [comment]
@jamieu _almost_ ...
@SimonLab if you have time tomorrow morning, would you mind helping to see if we can get CI to pass for this PR? (_please/thanks!_)

**Comment by SimonLab** [comment]
the application and tests are working fine on my machine, I think Travis struggle to build the application, I'll try to recreate the PR

**Comment by nelsonic** [comment]
@SimonLab thanks! will be good to get this merged in soon. ❤️

**Comment by SimonLab** [comment]
The issue seems to be due to the last version of foundation-site package (published yesterday)

**Comment by tobystokes** [comment]
we can keep it to foundation-sites to ~6.2 for now, nothing required from 6.3

**Comment by SimonLab** [comment]
@nelsonic tests are pasing now, and the issue was indeed linked to the new version of foundation-site. I will try to investigate what is breaking on their new version.

**Pull request merged**
