### PR TITLE
On display link

### PR DESCRIPTION
**Pull request by SimonLab**
link back to the search page
see #581 
to be merged after #591

### CODE REVIEW

**Comment by Danwhy** [comment]
LGTM, the codecov problem is because of my commit.

We should think about adding those test fixtures to the gitignore though

**Comment by nelsonic** [comment]
@SimonLab this PR _looks_ good. would you mind investigating/confirming why Travis-CI is failing for both commits on the branch? 🤔

**Comment by SimonLab** [comment]
The first commit failed because of the coverage (see [@Danwhy comment](https://github.com/TheScienceMuseum/collectionsonline/pull/592#issuecomment-262195929)). The second commit failed because it seems selenium didn't start properly with Travis, I'm just rerunning the tests I think it should resolved the issue

**Comment by nelsonic** [comment]
@SimonLab thanks for investigating it! 👍

**Comment by nelsonic** [comment]
@SimonLab thanks for updating. happy to merge. 👍

**Pull request merged**
