### PR TITLE
Removed 'user' relationship type from user relationship list

### PR DESCRIPTION
**Pull request by jamieu**
Small tweak to the users fixture to remove the 'user' relationships (as it was too vague in the interface).

### CODE REVIEW

**Comment by jamieu** [comment]
Is this failing due to to a test for the value I removed?

**Comment by Danwhy** [comment]
@jamie Probably, I'll have a look and fix it

**Comment by jamieu** [comment]
Sorry....I was trying to save you fixing a minor issue (and now your
debugging it).

[still will remind me what else i need to check in future, when making
changes like this...which is all good stuff]

**Comment by jamieu** [comment]
@Danwhy what was it?

**Comment by Danwhy** [comment]
It was actually a problem with some unrelated tests that were just failing because the index changed, nothing to do with what you did

**Comment by jamie** [comment]
@danwhy wrong @jamie.

**Comment by Danwhy** [comment]
Oops, sorry. Too many different usernames on different platforms

**Comment by nelsonic** [comment]
@jamieu looks good. merging. 👍

**Pull request merged**
