### PR TITLE
add gallery name in pillbox

### PR DESCRIPTION
**Pull request by SimonLab**
see #589

## To be merged after #630

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab please address merge conflicts and re-assign. thanks! 👍

**Comment by nelsonic** [comment]
@SimonLab this code looks good. if you can please _merge_ `master` into the branch [`#OneMoreTime`](https://www.youtube.com/watch?v=FGBhQbmPwH8) to reduce the `diff` and push up, _hopefully_ CodeCov will be happy and we can get this PR in today! 😉

**Comment by SimonLab** [comment]
@nelsonic the PR is now up to date

**Comment by nelsonic** [comment]
@SimonLab changes look good. merging. thanks! 👍

**Pull request merged**
