### PR TITLE
Codesign integration

### PR DESCRIPTION
**Pull request by Danwhy**
Moves src folder from codesign repo to collectionsonline.

@tobystokes 
Changes made to the src: 
* Pathnames for handlebar partials needed to be extended with directories to work with hapi
* Gulp file is gone, build is done with npm scripts instead
* Built files now go to __public__ folder, rather than dist 
* Handlebar templates are now served with hapi, rather than being built into static html
 * No longer using panini because of this, so had to add in some helper functions

No changes to the scss files.
Build is still done with `npm build` or `npm watch`
Server still started with `npm start` or `npm watch`

### CODE REVIEW

**Comment by alanshaw** [comment]
👓

**Comment by alanshaw** [comment]
@Danwhy could you update the README.md with the extra bower install step?

**Comment by Danwhy** [comment]
Oh yeah, shall do

**Comment by tobystokes** [comment]
You might be able to add bower install to npm postinstall script?
btw if it's a dependency too many, I expect all the bower packages have an npm equivalent.

**Comment by tobystokes** [comment]
`public/assets/icomoon` is redundant now, can be deleted

**Comment by alanshaw** [comment]
@tobystokes as you mentioned the plan is to remove bower so it's ok for now :)

**Comment by alanshaw** [comment]
@Danwhy I'm getting this on `npm install`:

```
> collectionsonline@1.0.0 build:css /Users/alan/Code/smg/collectionsonline
> node-sass src/assets/scss/main.scss public/bundle.css --include-path bower_components/foundation-sites/scss --include-path bower_components/slick-carousel/slick

{
  "formatted": "Error: File to import not found or unreadable: util/util\n       Parent style sheet: /Users/alan/Code/smg/collectionsonline/src/assets/scss/base/_foundation-settings.scss\n        on line 43 of src/assets/scss/base/_foundation-settings.scss\n>> @import 'util/util';\n   ^\n",
  "message": "File to import not found or unreadable: util/util\nParent style sheet: /Users/alan/Code/smg/collectionsonline/src/assets/scss/base/_foundation-settings.scss",
  "column": 1,
  "line": 43,
  "file": "/Users/alan/Code/smg/collectionsonline/src/assets/scss/base/_foundation-settings.scss",
  "status": 1
}
```

**Comment by alanshaw** [comment]
@Danwhy `public/assets/icons` - should these be `.gitignore`d?

**Comment by tobystokes** [comment]
@Danwhy that error is a missing file that should have been installed by bower...

**Comment by alanshaw** [comment]
oh so I have to bower install before npm install?

**Comment by Danwhy** [comment]
Ah maybe so. I should probably change the readme to the other way around

**Comment by tobystokes** [comment]
you would ahve to bower install before you npm run, install order shouldn't matter.

**Comment by Danwhy** [comment]
The icons are gitignored aren't they?

**Comment by alanshaw** [comment]
yes they are - apologies

**Comment by alanshaw** [comment]
I get lots of this when I `npm test`:

```
WARNING: vision failed to load helper '/Users/alan/Code/smg/collectionsonline/templates/helpers/lorem.js': Cannot find module 'helper-lorem'
```

**Comment by tobystokes** [comment]
That helper is probably redundant now too.
It was simply to generate a few lines of 'lorem ipsum...'

**Comment by alanshaw** [comment]
I think I'm missing a few icons
screen shot 2016-06-17 at 17 18 06

**Comment by alanshaw** [comment]
Should the header be this big?
screen shot 2016-06-17 at 17 18 31

**Comment by tobystokes** [comment]
<strike>`{{lorem count="5"}}`</strike>

https://github.com/TheScienceMuseum/collectionsonline/blob/codesign-integration/templates/pages/archivedoc.html#L62
https://github.com/TheScienceMuseum/collectionsonline/blob/codesign-integration/templates/pages/object.html#L90

**Comment by alanshaw** [comment]
@Danwhy the carousel and mega zoom are no longer working - I'd like to get this merged so can you fix up the few small issues above and submit a separate PR for that?

**Comment by tobystokes** [comment]
Those icons should be inheriting a class of icon-{{type}}
where type is object, person, archive etc.

**Comment by alanshaw** [comment]
@Danwhy this is awesome work BTW

**Comment by Danwhy** [comment]
@alanshaw Will do.

**Comment by Danwhy** [comment]
@tobystokes I think it's the data from the top of the page that's missing now. I'll have to pass it in seperately

**Comment by tobystokes** [comment]
I think carousel would work if bundle.js was included on page?

**Comment by Danwhy** [comment]
@tobystokes It should do, I was just having a little trouble with bower. Should be able to get it all working though

**Comment by tobystokes** [comment]
But yep all generally good, I can run it fine, so can continue on Monday, thanks!

**Comment by Danwhy** [comment]
@alanshaw this should be good now. I'll try to get the carousel etc working by Monday

**Comment by alanshaw** [comment]
Ok I'll have a quick check now

**Comment by alanshaw** [comment]
LGTM

**Pull request merged**
